// packages/app/src/app/components/ui/drag-image/drag-image.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core'
import { DragImageService } from 'src/app/services/drag-image.service'

@Component({
  selector: 'app-drag-image',
  templateUrl: './drag-image.component.html',
})
export class DragImageComponent implements AfterViewInit {
  @ViewChild('container') container!: ElementRef<HTMLDivElement>

  constructor(public dragImage: DragImageService) {}

  ngAfterViewInit(): void {
    this.dragImage.element = this.container.nativeElement
  }
}

<div class="black-hole">
  <div
    #container
    class="bg-primary-700 absolute inline-flex space-x-1 whitespace-nowrap rounded px-1.5 py-0.5 text-xs text-white drop-shadow"
  >
    <span id="drag-image-label">{{ dragImage.label }}</span>
  </div>
</div>

// src/runtime/components/misc/DragImage.vue
<template>
  <div
    id="pruvious-drag-image"
    class="absolute inline-flex space-x-1 whitespace-nowrap rounded bg-primary-700 px-1.5 py-0.5 text-xs text-white drop-shadow"
  >
    <span>{{ dragImageLabel }}</span>
  </div>
</template>

<script lang="ts" setup>
import { useDragImageLabel } from '../../composables/dashboard/move'

const dragImageLabel = useDragImageLabel()
</script>
