// src/runtime/components/misc/MediaBreadcrumbs.vue
<template>
  <ul class="flex gap-1 overflow-hidden text-sm">
    <li>
      <button
        v-if="directory"
        :title="__('pruvious-dashboard', 'Open root folder')"
        @click="$emit('openDirectory', '')"
        data-ignore-autofocus
        type="button"
        class="text-gray-400 outline-none transition hocus:text-primary-700"
      >
        {{ rootLabel }}
      </button>

      <span v-if="!directory" :title="__('pruvious-dashboard', 'Root folder')">{{ rootLabel }}</span>
    </li>

    <li
      v-for="{ name, path } of parentDirectories"
      class="flex gap-1 overflow-hidden truncate before:font-normal before:text-gray-400 before:content-['/']"
    >
      <button
        :title="__('pruvious-dashboard', 'Open $item', { item: name })"
        @click="$emit('openDirectory', path)"
        data-ignore-autofocus
        type="button"
        class="truncate text-gray-400 outline-none transition hocus:text-primary-700"
      >
        {{ name }}
      </button>
    </li>

    <li
      v-if="currentDirectoryName"
      class="flex gap-1 truncate before:font-normal before:text-gray-400 before:content-['/']"
    >
      <span class="truncate">{{ currentDirectoryName }}</span>
    </li>
  </ul>
</template>

<script lang="ts" setup>
import { ref, watch } from '#imports'
import type { MediaDirectory } from '../../composables/dashboard/media'
import { __, loadTranslatableStrings } from '../../composables/translatable-strings'

const props = defineProps({
  directory: {
    type: String,
    required: true,
  },
  rootLabel: {
    type: String,
    required: true,
  },
})

defineEmits<{
  openDirectory: [string]
}>()

const currentDirectoryName = ref('')
const parentDirectories = ref<MediaDirectory[]>([])

await loadTranslatableStrings('pruvious-dashboard')

watch(
  () => props.directory,
  () => {
    const directories = props.directory.split('/').filter(Boolean)

    currentDirectoryName.value = directories[directories.length - 1] || ''
    parentDirectories.value = directories.slice(0, -1).map((directory, i) => {
      const path = directories.slice(0, i + 1).join('/')
      return { name: directory, path: path ? `${path}/` : '' }
    })
  },
  { immediate: true },
)
</script>

// packages/app/src/app/components/media/media-breadcrumbs/media-breadcrumbs.component.ts
import { Component, EventEmitter, Input, OnChanges, Output, SimpleChanges } from '@angular/core'
import { clearArray } from '@pruvious/utils'
import { ToastrService } from 'ngx-toastr'
import { forkJoin, takeUntil } from 'rxjs'
import { BaseComponent } from 'src/app/components/base.component'
import { ApiService, Directory } from 'src/app/services/api.service'

@Component({
  selector: 'app-media-breadcrumbs',
  templateUrl: './media-breadcrumbs.component.html',
})
export class MediaBreadcrumbsComponent extends BaseComponent implements OnChanges {
  @Input()
  directory?: Partial<Directory>

  @Input()
  rootLabel: string = 'Library'

  @Output()
  openRoot = new EventEmitter<void>()

  @Output()
  openDirectory = new EventEmitter<Partial<Directory>>()

  tree: Partial<Directory>[] = []

  constructor(protected api: ApiService, protected toastr: ToastrService) {
    super()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['directory']) {
      clearArray(this.tree)

      const pathParts = this.directory?.path?.split('/').slice(0, -1)

      if (pathParts?.length) {
        this.tree.push(...pathParts.map((pathPart) => ({ name: pathPart })))

        const observables = Object.fromEntries(
          pathParts.map((_, index) => [
            index,
            this.api.getDirectoryByPath(pathParts.slice(0, index + 1).join('/')),
          ]),
        )

        forkJoin(observables)
          .pipe(takeUntil(this.unsubscribeAll$))
          .subscribe({
            next: (directories) => {
              clearArray(this.tree)

              Object.keys(directories)
                .sort()
                .forEach((index) => this.tree.push(directories[index]))
            },
            error: () => {
              this.toastr.error(
                'There was an error retrieving the media library tree (reload the app to resolve this issue)',
              )
            },
          })
      }
    }
  }
}

<ul class="flex gap-1 overflow-hidden text-sm">
  <li>
    <button
      *ngIf="directory"
      (click)="openRoot.emit()"
      class="hocus:text-primary-700 text-gray-400 outline-none transition"
      data-autofocus-ignore
      title="Open root folder"
      type="button"
    >
      {{ rootLabel }}
    </button>

    <span *ngIf="!directory" title="Root folder">{{ rootLabel }}</span>
  </li>

  <li
    *ngFor="let directory of tree"
    class="flex gap-1 overflow-hidden truncate before:font-normal before:text-gray-400 before:content-['/']"
  >
    <button
      [title]="'Open ' + directory.name"
      (click)="directory.id && openDirectory.emit(directory)"
      class="hocus:text-primary-700 truncate text-gray-400 outline-none transition"
      data-autofocus-ignore
      type="button"
    >
      {{ directory.name }}
    </button>
  </li>

  <li
    *ngIf="directory"
    class="flex gap-1 truncate before:font-normal before:text-gray-400 before:content-['/']"
  >
    <span class="truncate">{{ directory.name }}</span>
  </li>
</ul>
